-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS resepti CASCADE;
DROP TABLE IF EXISTS kokkaaja CASCADE;
DROP TABLE IF EXISTS raakaaine CASCADE;
DROP TABLE IF EXISTS rakategoria CASCADE;
DROP TABLE IF EXISTS ainekset CASCADE;