-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS kokkaajat CASCADE;
DROP TABLE IF EXISTS rakategoriat CASCADE;
DROP TABLE IF EXISTS raakaaineet CASCADE;
DROP TABLE IF EXISTS reseptit CASCADE;
DROP TABLE IF EXISTS ainekset CASCADE;